---
title: Quinn Cantwell
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  stills:
    title: Stills
    output: true
    permalink: "/stills/:path/"
  uploads:
    title: Uploads
    output: true
    permalink: "/uploads/:path/"
  videos:
    title: Videos
    output: true
    permalink: "/videos/:path/"
defaults:
- scope:
    path: ''
    type: stills
  values:
    title: 
    categories: stills
    thumbnail_image: 
    gallery:
    - file: 
    layout: stills
- scope:
    path: ''
    type: videos
  values:
    title: 
    categories: videos
    thumbnail_image: 
    videos:
    - url: 
    layout: videos
email: quinn.cagney@gmail.com
description: Quinn Cantwell is a Nashville-based art director.
tags: Everlane, Art Director, Quinn Cantwell, Design, Director, Digital, Photography
baseurl: "/"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
